---
kind: Service
apiVersion: v1
metadata:
  name: springservice
spec:
  selector:
    app: course-api
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
      nodePort: 30001
  type: LoadBalancer



---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springappdeployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: course-api
    spec:
      containers:
        - name: course-api
          image: docker-course-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081               